### ISSUE TITLE
Error: Cannot find module '/home/functionalJS/node_modules/coderoad-functional-school/tutorial/data\students.json'

### ISSUE THREAD

**Issue by minicast** [coderoad/coderoad-functional-school#2]
I get the error below when running the tutorial.

```
/home/functionalJS/node_modules/mocha-coderoad/lib/runner.js:36 test error module.js:338
    throw err;
    ^

Error: Cannot find module '/home/functionalJS/node_modules/coderoad-functional-school/tutorial/data\students.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadGlobal (/home/functionalJS/node_modules/mocha-coderoad/lib/loaders.js:12:20)
    at Object.<anonymous> (/home/functionalJS/node_modules/coderoad-functional-school/tutorial/.tmp.js:7:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/functionalJS/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/functionalJS/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/functionalJS/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/functionalJS/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
```

however, after I comment line `20` in `/home/node_modules/mocha-coderoad/lib/loaders.js`everything works fine : 

``` // pathTo = pathTo.replace(/\//g, '\\');```

(probably the file path should not be normalized twice in linux)

**Comment by ShMcK** [comment]
Thanks! 

I put out a [new release of mocha-coderoad](https://github.com/coderoad/mocha-coderoad/releases/tag/v0.5.4) that doesn't normalize paths twice for Mac or Linux.

`> npm install mocha-coderoad` should provide you the latest version.
