### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by minicast** [coderoad/coderoad-functional-school#3]
when saving `06-concat.js` (at the first task) the following error pops up:

```
/home/functionalJS/node_modules/mocha-coderoad/lib/runner.js:36 test error path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:448:3)
    at getCrossPlatformPath (/home/functionalJS/node_modules/mocha-coderoad/lib/loaders.js:15:19)
    at loadGlobal (/home/functionalJS/node_modules/mocha-coderoad/lib/loaders.js:11:54)
    at Object.<anonymous> (/home/functionalJS/node_modules/coderoad-functional-school/tutorial/.tmp.js:4:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/functionalJS/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/functionalJS/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/functionalJS/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/home/functionalJS/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
```

now running `mocha-coderoad@0.5.4` (but I also got this error before updating)

**Comment by ShMcK** [comment]
I'll release a new version of the tutorial with a fix, but if you don't want to lose your current progress for now, try this:

go into *node_modules/coderoad-functional-school/tutorial/1/06/01-concat.spec.js* and make the following change:

```js
// loadGlobal('data/courses2.json'); 
loadGlobal('courses', 'data/courses2.json');
```
